# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under theterms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General ublic License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the Odoo plugin for Dia


from odoo import models, fields, api, _
from odoo.exceptions import UserError


class Invoice_extended(models.Model):
    _inherit = "account.invoice"

    ir_sequence_id = fields.Many2one('ir.sequence')
    invoice_sequence = fields.Char('Numero de Control', readonly=True)
    supplier_control_number = fields.Char('Numero de Control', default=00000)
    invoice_number = fields.Char('Numero de Factura')

    @api.model
    def create(self, vals):
        seq = self.env['ir.sequence'].get('invoice.number') or '/'
        vals['Invoice_sequence'] = seq
        return super(Invoice_extended, self).create(vals)

